# Generated by Django 5.0.2 on 2024-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('mon', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('thu', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fri', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sun', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
