version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: nginx-conf/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django